src = [
    'src',
    'fastapi-kgf'
]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 79
indent-width = 4

# Assume Python 3.9
target-version = "py313"


[lint]
select = [
	"FAST", # FastAPI (FAST)
	"F", # Pyflakes (F)
	"W", # pycodestyle Warning (W)
	"E", # pycodestyle Error (E)
	"I", # isort (I)
	"UP", # pyupgrade (UP)
	"C4", # flake8-comprehensions (C4)
	"FA", # flake9-future-annotations
	"ISC",  # flake8-implicit-str-concat (ISC)
	"ICN", # flake8-import-conventions (ICN)
	"RET", # flake8-return (RET)
	"SIM", # flake8-simplify (SIM)
	"TID", # flake8-tidy-imports
	"TC", # flake8-type-checking
	"PTH", # flake8-use-pathlib (PTH)
	"TD", # flake8-todos
	"COM", # flake8-commas (COM)
	"DTZ", # flake8-datetimez (DTZ)
	"FBT", # flake8-boolean-trap (FBT)
	"N", # pep8-naming (N)
	"Q", # flake8-quotes (Q)
	"RUF", # Ruff-specific rules (RUF)
	"PYI", # flake8-pyi (PYI)
	"PLW", # Pylint Warning (PLW)
	"LOG", # flake8-logging (LOG)
	"B", # flake8-bugbear (B)
	"AIR", # airflow (AIR)
	"YTT", # flake8-2020 (YTT)
	"ANN", # flake8-annotations (ANN)
	# "ASYNC",
	"S", # flake8-bandit (S)
	"BLE", # flake8-blind-except (BLE)
	"T10", # flake8-debugger (T10)
	"EM", # flake8-errmsg (EM)
	"INP", # flake8-no-pep420 (INP)
	"PIE", # flake8-pie (PIE)
	"T20", # flake8-print (T20)
	# "PT",  # flake8-pytest-style (PT)
	"RSE", # flake8-raise (RSE)
	"SLF", # flake8-self (SLF)
	"SLOT", # flake8-slots (SLOT)
	"ARG", # flake8-unused-arguments (ARG)
	"FLY", # flynt (FLY)
	"TRY", # tryceratops (TRY)
	"PLR", # Pylint Refactor (PLR)
	"PLE", # Pylint Error (PLE)
	"PGH", # pygrep-hooks
	"G", # flake8-logging-format (G)
	"C90", # mccabe (C90)
	"PERF", # Perflint (PERF)
	"FURB" # refurb (FURB)
]

[lint.per-file-ignores]
"fastapi-kgf/core/schemas/programs.py" = ['RUF002']
"fastapi-kgf/app_lifespan.py" = ["ARG001", "PGH003"]
"fastapi-kgf/core/schemas/user.py" = ["RUF002"]
"fastapi-kgf/core/models/user.py" = ["ARG002"]
"fastapi-kgf/rest/main_views.py" = ["E501"]
"fastapi-kgf/parsers/platforms/tek_torg/parser.py" = ["RUF002"]

